services:

  db-postgres-test:
    image: postgres:17
    container_name: ${DB_CONTAINER_NAME}
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    tmpfs:
      - /var/lib/postgresql/data
